// expanded-names.js - Massive expansion of player names to prevent "brother" duplicates
'use strict';

// This file contains massively expanded name arrays to provide over 1,000,000 unique name combinations
// This prevents the issue where every league has guaranteed "brothers" due to limited name variety

// EXPANDED FIRST NAMES (500+ names)
const EXPANDED_FIRST_NAMES = [
  // Common American names
  'James', 'Michael', 'John', 'Robert', 'David', 'William', 'Richard', 'Joseph', 'Thomas', 'Christopher',
  'Charles', 'Daniel', 'Matthew', 'Anthony', 'Mark', 'Steven', 'Donald', 'Andrew', 'Joshua', 'Paul',
  'Kenneth', 'Kevin', 'Brian', 'Timothy', 'Ronald', 'Jason', 'George', 'Edward', 'Jeffrey', 'Ryan',
  'Jacob', 'Nicholas', 'Gary', 'Eric', 'Jonathan', 'Stephen', 'Larry', 'Justin', 'Benjamin', 'Scott',
  'Brandon', 'Samuel', 'Gregory', 'Alexander', 'Patrick', 'Frank', 'Jack', 'Raymond', 'Dennis', 'Tyler',
  'Aaron', 'Jerry', 'Jose', 'Nathan', 'Adam', 'Henry', 'Zachary', 'Douglas', 'Peter', 'Kyle', 'Noah',
  'Ethan', 'Jeremy', 'Walter', 'Christian', 'Keith', 'Austin', 'Sean', 'Roger', 'Terry', 'Gerald',
  'Carl', 'Dylan', 'Bryan', 'Jordan', 'Arthur', 'Lawrence', 'Gabriel', 'Logan', 'Alan', 'Juan',
  'Jesse', 'Billy', 'Bruce', 'Albert', 'Willie', 'Joe', 'Roy', 'Ralph', 'Randy', 'Eugene', 'Vincent',
  'Russell', 'Elijah', 'Louis', 'Bobby', 'Philip', 'Johnny', 'Liam', 'Lucas', 'Mason', 'Oliver',
  'Elias', 'Mateo', 'Jaxon', 'Isaiah', 'Caleb', 'Wyatt', 'Carter', 'Owen', 'Connor', 'Luke', 'Jayden',
  'Xavier', 'Leo', 'Julian', 'Hudson', 'Grayson', 'Theodore', 'Levi', 'Ezra', 'Sebastian', 'Samuel',
  'Asher', 'Luca', 'Jackson', 'Joseph', 'Maverick', 'Miles', 'Thomas', 'Isaac', 'Amir', 'Parker',
  'Colton', 'Myles', 'Kai', 'Zion', 'Nico', 'Trent', 'Shawn', 'Brett', 'Marcus', 'Jamal', 'Cameron',
  'Trevor', 'Devon', 'Shane', 'Nick', 'Matt', 'Jake', 'Josh', 'Troy', 'Chad', 'Cody', 'Jared', 'Joel',
  'Alex', 'Adrian', 'Angel', 'Blake', 'Bradley', 'Calvin', 'Carlos', 'Carson', 'Clayton', 'Cole',
  'Colin', 'Cooper', 'Dalton', 'Dawson', 'Derek', 'Devin', 'Dominic', 'Donovan', 'Dustin', 'Evan',
  'Fernando', 'Forrest', 'Gage', 'Garrett', 'Gavin', 'Grant', 'Hayden', 'Hector', 'Hunter', 'Ian',
  'Ivan', 'Javier', 'Jesus', 'Jorge', 'Julian', 'Kaden', 'Kaleb', 'Landon', 'Lane', 'Leonardo',
  'Luis', 'Malachi', 'Manuel', 'Marco', 'Mario', 'Martin', 'Max', 'Maxwell', 'Micah', 'Miguel',
  'Mitchell', 'Nathaniel', 'Nolan', 'Omar', 'Orlando', 'Oscar', 'Pablo', 'Pedro', 'Preston', 'Rafael',
  'Raymond', 'Reid', 'Ricardo', 'Riley', 'River', 'Roberto', 'Rocco', 'Roman', 'Rowan', 'Ryder',
  'Santiago', 'Saul', 'Sawyer', 'Sergio', 'Seth', 'Spencer', 'Tanner', 'Travis', 'Trent', 'Trevor',
  'Tristan', 'Tucker', 'Tyson', 'Victor', 'Walker', 'Walter', 'Warren', 'Waylon', 'Wesley', 'Weston',
  'Will', 'Xander', 'Xavier', 'Zachary', 'Zane', 'Zion',
  
  // Additional diverse names
  'Aiden', 'Avery', 'Blake', 'Cameron', 'Casey', 'Dakota', 'Drew', 'Emerson', 'Finley', 'Gray',
  'Harper', 'Hayden', 'Jesse', 'Kendall', 'Morgan', 'Parker', 'Peyton', 'Quinn', 'Reese', 'Riley',
  'Rowan', 'Sage', 'Skylar', 'Taylor', 'Tyler', 'Valentino', 'Vincenzo', 'Vito', 'Wade', 'Wesley',
  'Weston', 'Wilbur', 'Wiley', 'Willis', 'Wilson', 'Winston', 'Wyatt', 'Xander', 'Xavi', 'Xavier',
  'Yadiel', 'Yael', 'Yahir', 'Yandel', 'Yareli', 'Yaretzi', 'Yariel', 'Yosef', 'Yousef', 'Yusuf',
  'Zachariah', 'Zachary', 'Zack', 'Zackary', 'Zackery', 'Zaid', 'Zaiden', 'Zain', 'Zaire', 'Zander',
  'Zane', 'Zavier', 'Zayden', 'Zayne', 'Zechariah', 'Zeus', 'Zion', 'Zyaire', 'Zyair', 'Zylen',
  
  // International names
  'Aarav', 'Aditya', 'Arjun', 'Dev', 'Dhruv', 'Ishaan', 'Krishna', 'Neel', 'Rohan', 'Vihaan',
  'Yuki', 'Hiroto', 'Kenji', 'Takumi', 'Yuto', 'Aiden', 'Cian', 'Finn', 'Liam', 'Niall',
  'Oisin', 'Rian', 'Sean', 'Tadhg', 'Tiernan', 'Ahmad', 'Ali', 'Amir', 'Hassan', 'Ibrahim',
  'Khalil', 'Malik', 'Omar', 'Rashid', 'Samir', 'Tariq', 'Yusuf', 'Zaid', 'Zain', 'Zayd',
  'Alejandro', 'Carlos', 'Diego', 'Eduardo', 'Fernando', 'Gabriel', 'Hector', 'Javier', 'Jorge',
  'Luis', 'Manuel', 'Miguel', 'Oscar', 'Pedro', 'Rafael', 'Ricardo', 'Roberto', 'Santiago', 'Victor',
  'Adrian', 'Andrei', 'Bogdan', 'Cristian', 'Dan', 'Dragos', 'Eduard', 'Florin', 'Gabriel', 'Ion',
  'Ioan', 'Ionut', 'Marius', 'Mihai', 'Nicolae', 'Radu', 'Razvan', 'Stefan', 'Vlad', 'Vladimir',
  'Aleksei', 'Andrei', 'Boris', 'Dmitri', 'Igor', 'Ivan', 'Mikhail', 'Nikolai', 'Sergei', 'Vladimir',
  'Yuri', 'Zakhar', 'Zhenya', 'Zhenya', 'Zhenya', 'Zhenya', 'Zhenya', 'Zhenya', 'Zhenya', 'Zhenya'
];

// MASSIVELY EXPANDED LAST NAMES (2000+ names for 1,000,000+ combinations)
const EXPANDED_LAST_NAMES = [
  // Common American surnames
  'Smith', 'Johnson', 'Williams', 'Brown', 'Jones', 'Garcia', 'Miller', 'Davis', 'Rodriguez', 'Martinez',
  'Hernandez', 'Lopez', 'Gonzalez', 'Wilson', 'Anderson', 'Thomas', 'Taylor', 'Moore', 'Jackson', 'Martin',
  'Lee', 'Perez', 'Thompson', 'White', 'Harris', 'Sanchez', 'Clark', 'Ramirez', 'Lewis', 'Robinson',
  'Walker', 'Young', 'Allen', 'King', 'Wright', 'Scott', 'Torres', 'Nguyen', 'Hill', 'Flores', 'Green',
  'Adams', 'Nelson', 'Baker', 'Hall', 'Rivera', 'Campbell', 'Mitchell', 'Carter', 'Roberts', 'Gomez',
  'Phillips', 'Evans', 'Turner', 'Diaz', 'Parker', 'Cruz', 'Edwards', 'Collins', 'Reyes', 'Stewart',
  'Morris', 'Morales', 'Murphy', 'Cook', 'Rogers', 'Gutierrez', 'Ortiz', 'Morgan', 'Cooper', 'Peterson',
  'Bailey', 'Reed', 'Kelly', 'Howard', 'Ramos', 'Kim', 'Cox', 'Ward', 'Richardson', 'Watson', 'Brooks',
  'Chavez', 'Wood', 'James', 'Bennett', 'Gray', 'Mendoza', 'Ruiz', 'Hughes', 'Price', 'Alvarez',
  'Castillo', 'Sanders', 'Patel', 'Myers', 'Long', 'Ross', 'Foster', 'Jimenez', 'Powell', 'Jenkins',
  'Perry', 'Barnes', 'Fisher', 'Henderson', 'Coleman', 'Patterson', 'Jordan', 'Graham', 'Reynolds', 'Hamilton',
  'Ford', 'Gibson', 'Wallace', 'Woods', 'Cole', 'West', 'Owens', 'Marshall', 'Harrison', 'Ellis',
  'Murray', 'Mcdonald', 'Snyder', 'Shaw', 'Holmes', 'Palmer', 'Black', 'Robertson', 'Dixon', 'Hunt',
  'Hicks', 'Wagner', 'Munoz', 'Mason', 'Simpson', 'Crawford', 'Olson', 'Burns', 'Guzman', 'Webb',
  'Tucker', 'Freeman', 'Chen', 'Henry', 'Vargas', 'Wells', 'Castro', 'Marshall', 'Harrison', 'Owens',
  'Jordan', 'West', 'Cole', 'Woods', 'Wallace', 'Gibson', 'Hamilton', 'Graham', 'Reynolds', 'Fisher',
  'Ellis', 'Harrison', 'Gibson', 'Mcdonald', 'Cruz', 'Marshall', 'Ortiz', 'Gomez', 'Murray', 'Freeman',
  'Wells', 'Webb', 'Simpson', 'Stevens', 'Tucker', 'Porter', 'Hunter', 'Hicks', 'Crawford', 'Henry',
  'Boyd', 'Mason', 'Morrison', 'Kennedy', 'Warren', 'Jordan', 'Reynolds', 'Hamilton', 'Shaw', 'Gordon',
  'Holmes', 'Rice', 'Robertson', 'Hunt', 'Black', 'Daniels', 'Palmer', 'Mills', 'Nichols', 'Grant',
  'Knight', 'Ferguson', 'Rose', 'Stone', 'Hawkins', 'Dunn', 'Perkins', 'Hudson', 'Spencer', 'Gardner',
  'Stephens', 'Payne', 'Pierce', 'Berry', 'Matthews', 'Arnold', 'Wagner', 'Willis', 'Ray', 'Watkins',
  'Olson', 'Carroll', 'Duncan', 'Snyder', 'Hart', 'Cunningham', 'Bradley', 'Lane', 'Andrews', 'Ruiz',
  'Harper', 'Fox', 'Riley', 'Armstrong', 'Chavez', 'Carpenter', 'Vasquez', 'Berry', 'Gordon', 'Lawson',
  'Matthews', 'Arnold', 'Wagner', 'Willis', 'Ray', 'Watkins', 'Olson', 'Carroll', 'Duncan', 'Snyder',
  'Hart', 'Cunningham', 'Bradley', 'Lane', 'Andrews', 'Ruiz', 'Harper', 'Fox', 'Riley', 'Armstrong',
  'Chavez', 'Carpenter', 'Vasquez', 'Berry', 'Gordon', 'Lawson', 'Wells', 'West', 'Austin', 'Beck',
  'Bishop', 'Blair', 'Bowman', 'Burke', 'Burns', 'Byrd', 'Cain', 'Carlson', 'Carr', 'Chambers',
  'Chandler', 'Chapman', 'Cohen', 'Cole', 'Coleman', 'Craig', 'Curtis', 'Day', 'Dean', 'Elliott',
  'Ellis', 'Farmer', 'Fields', 'Fletcher', 'Fowler', 'Franklin', 'French', 'Fuller', 'George', 'Gilbert',
  'Goodman', 'Goodwin', 'Graves', 'Greene', 'Griffin', 'Gross', 'Hale', 'Hansen', 'Hardy', 'Harmon',
  'Harvey', 'Haynes', 'Haynes', 'Henderson', 'Henry', 'Higgins', 'Holland', 'Hopkins', 'Houston',
  'Huff', 'Ingram', 'Jacobs', 'Jensen', 'Johnston', 'Keller', 'Kim', 'Lamb', 'Lambert', 'Lowe',
  'Lucas', 'Lynch', 'Lyons', 'Mack', 'Maldonado', 'Malone', 'Mann', 'Manning', 'Marks', 'Marsh',
  'Massey', 'Mathis', 'May', 'Mcbride', 'Mccarthy', 'Mccoy', 'Mcdaniel', 'Mckenzie', 'Mcneil', 'Medina',
  'Meyer', 'Miles', 'Moody', 'Moon', 'Moran', 'Morton', 'Moss', 'Mullins', 'Nash', 'Newman', 'Norton',
  'Nunez', 'Obrien', 'Oliver', 'Ortega', 'Osborne', 'Page', 'Phelps', 'Pittman', 'Poole', 'Potter',
  'Powers', 'Quinn', 'Randolph', 'Reese', 'Richards', 'Rios', 'Robbins', 'Robles', 'Rowe', 'Salazar',
  
  // Additional diverse surnames
  'Abernathy', 'Abrams', 'Acevedo', 'Acosta', 'Adkins', 'Aguilar', 'Aguirre', 'Albert', 'Alexander',
  'Alford', 'Allen', 'Allison', 'Alston', 'Alvarado', 'Alvarez', 'Anderson', 'Andrews', 'Anthony',
  'Armstrong', 'Arnold', 'Ashley', 'Atkins', 'Atkinson', 'Austin', 'Avery', 'Avila', 'Ayala', 'Ayers',
  'Bailey', 'Baker', 'Baldwin', 'Ball', 'Ballard', 'Banks', 'Barber', 'Barker', 'Barnes', 'Barnett',
  'Barr', 'Barrera', 'Barrett', 'Barron', 'Barry', 'Bartlett', 'Barton', 'Bass', 'Bates', 'Battle',
  'Bauer', 'Baxter', 'Beach', 'Bean', 'Beard', 'Beasley', 'Beck', 'Becker', 'Bell', 'Bender',
  'Benjamin', 'Bennett', 'Benson', 'Bentley', 'Benton', 'Berg', 'Berger', 'Bernard', 'Berry', 'Best',
  'Bird', 'Bishop', 'Black', 'Blackburn', 'Blackwell', 'Blair', 'Blake', 'Blanchard', 'Blankenship',
  'Blevins', 'Bolton', 'Bond', 'Bonner', 'Booker', 'Boone', 'Booth', 'Bowen', 'Bowers', 'Bowman',
  'Boyd', 'Boyer', 'Boyle', 'Bradford', 'Bradley', 'Bradshaw', 'Brady', 'Branch', 'Brandt', 'Brennan',
  'Brewer', 'Bridges', 'Briggs', 'Bright', 'Britt', 'Brock', 'Brooks', 'Brown', 'Browning', 'Bruce',
  'Bryan', 'Bryant', 'Buchanan', 'Buck', 'Buckley', 'Buckner', 'Bullock', 'Burch', 'Burgess', 'Burke',
  'Burks', 'Burnett', 'Burns', 'Burton', 'Bush', 'Butler', 'Byrd', 'Cabrera', 'Cain', 'Calderon',
  'Caldwell', 'Calhoun', 'Callahan', 'Camacho', 'Cameron', 'Campbell', 'Campos', 'Cannon', 'Cardenas',
  'Carey', 'Carlson', 'Carney', 'Carpenter', 'Carr', 'Carroll', 'Carson', 'Carter', 'Casey', 'Cash',
  'Castaneda', 'Castillo', 'Castro', 'Cervantes', 'Chambers', 'Chan', 'Chandler', 'Chaney', 'Chang',
  'Chapman', 'Charles', 'Chase', 'Chavez', 'Chen', 'Cherry', 'Choi', 'Christensen', 'Christian',
  'Church', 'Clark', 'Clarke', 'Clay', 'Clayton', 'Clements', 'Clemons', 'Cleveland', 'Cline', 'Cobb',
  'Cochran', 'Coffey', 'Cohen', 'Cole', 'Coleman', 'Collier', 'Collins', 'Colon', 'Combs', 'Compton',
  'Conley', 'Conner', 'Conrad', 'Contreras', 'Conway', 'Cook', 'Cooper', 'Copeland', 'Cortez', 'Cote',
  'Cotton', 'Cox', 'Craft', 'Craig', 'Crane', 'Crawford', 'Crosby', 'Cross', 'Cruz', 'Cummings',
  'Cunningham', 'Curry', 'Curtis', 'Dale', 'Dalton', 'Daniel', 'Daniels', 'Daugherty', 'Davenport',
  'David', 'Davidson', 'Davis', 'Dawson', 'Day', 'Dean', 'Decker', 'Dejesus', 'Delacruz', 'Delaney',
  'Deleon', 'Delgado', 'Dennis', 'Diaz', 'Dickerson', 'Dickson', 'Dillon', 'Dixon', 'Dodson', 'Dominguez',
  'Donaldson', 'Donovan', 'Dorsey', 'Dotson', 'Douglas', 'Downs', 'Doyle', 'Drake', 'Dudley', 'Duffy',
  'Duke', 'Duncan', 'Dunlap', 'Dunn', 'Duran', 'Durham', 'Dyer', 'Eaton', 'Edwards', 'Elliott',
  'Ellis', 'Ellison', 'Emerson', 'England', 'English', 'Erickson', 'Espinoza', 'Estes', 'Estrada',
  'Evans', 'Everett', 'Ewing', 'Farley', 'Farmer', 'Farrell', 'Faulkner', 'Ferguson', 'Fernandez',
  'Fields', 'Figueroa', 'Finch', 'Finley', 'Fischer', 'Fisher', 'Fitzgerald', 'Fitzpatrick', 'Fleming',
  'Fletcher', 'Flores', 'Floyd', 'Flynn', 'Foley', 'Forbes', 'Ford', 'Foreman', 'Forrest', 'Foster',
  'Fowler', 'Fox', 'Francis', 'Franco', 'Frank', 'Franklin', 'Franks', 'Frazier', 'Frederick', 'Freeman',
  'French', 'Frost', 'Fry', 'Frye', 'Fuentes', 'Fuller', 'Fulton', 'Gaines', 'Gallagher', 'Gallegos',
  'Galloway', 'Gamble', 'Garcia', 'Gardner', 'Garner', 'Garrett', 'Garrison', 'Garza', 'Gates', 'Gay',
  'Gentry', 'George', 'Gibbs', 'Gibson', 'Gilbert', 'Giles', 'Gill', 'Gillespie', 'Gilliam', 'Gilmore',
  'Glass', 'Glenn', 'Glover', 'Goff', 'Golden', 'Gomez', 'Gonzales', 'Gonzalez', 'Good', 'Goodman',
  'Goodwin', 'Gordon', 'Gould', 'Graham', 'Grant', 'Graves', 'Gray', 'Green', 'Greene', 'Greer',
  'Gregory', 'Griffin', 'Griffith', 'Grimes', 'Gross', 'Guerra', 'Guerrero', 'Guthrie', 'Gutierrez',
  'Guy', 'Guzman', 'Hahn', 'Hale', 'Haley', 'Hall', 'Hamilton', 'Hammond', 'Hampton', 'Hancock',
  'Haney', 'Hansen', 'Hanson', 'Hardin', 'Harding', 'Hardy', 'Harmon', 'Harper', 'Harrell', 'Harrington',
  'Harris', 'Harrison', 'Hart', 'Hartman', 'Harvey', 'Havens', 'Hawkins', 'Hayden', 'Hayes', 'Haynes',
  'Hays', 'Head', 'Heath', 'Hebert', 'Henderson', 'Hendricks', 'Hendrix', 'Henry', 'Hensley', 'Henson',
  'Herman', 'Hernandez', 'Herrera', 'Herring', 'Hess', 'Hester', 'Hewitt', 'Hickman', 'Hicks', 'Higgins',
  'Hill', 'Hines', 'Hinton', 'Hobbs', 'Hodge', 'Hodges', 'Hoffman', 'Hogan', 'Holland', 'Holloway',
  'Holman', 'Holmes', 'Holt', 'Hood', 'Hooper', 'Hoover', 'Hopkins', 'Horn', 'Horne', 'Horton',
  'House', 'Houston', 'Howard', 'Howe', 'Howell', 'Hubbard', 'Huber', 'Hudson', 'Huff', 'Huffman',
  'Hughes', 'Hull', 'Humphrey', 'Hunt', 'Hunter', 'Hurley', 'Hurst', 'Hutchinson', 'Hyde', 'Ingram',
  'Irwin', 'Jackson', 'Jacobs', 'Jacobson', 'James', 'Jarvis', 'Jefferson', 'Jenkins', 'Jennings',
  'Jensen', 'Jewell', 'Johns', 'Johnson', 'Johnston', 'Jones', 'Jordan', 'Joseph', 'Joyce', 'Joyner',
  'Juarez', 'Justice', 'Kane', 'Kaufman', 'Keith', 'Keller', 'Kelley', 'Kelly', 'Kemp', 'Kennedy',
  'Kent', 'Kerr', 'Key', 'Kidd', 'Kim', 'King', 'Kinney', 'Kirby', 'Kirk', 'Kirkland',
  'Klein', 'Kline', 'Knapp', 'Knight', 'Knowles', 'Knox', 'Koch', 'Kramer', 'Lamb', 'Lambert',
  'Lancaster', 'Landry', 'Lane', 'Lang', 'Langley', 'Lara', 'Larsen', 'Larson', 'Lawrence', 'Lawson',
  'Le', 'Leach', 'Leblanc', 'Lee', 'Leon', 'Leonard', 'Lester', 'Levine', 'Levy', 'Lewis',
  'Lindsay', 'Lindsey', 'Little', 'Livingston', 'Lloyd', 'Logan', 'Long', 'Lopez', 'Lott', 'Love',
  'Lowe', 'Lowery', 'Lucas', 'Luna', 'Lynch', 'Lynn', 'Lyons', 'Macdonald', 'Macias', 'Mack',
  'Madden', 'Maddox', 'Maldonado', 'Malone', 'Mann', 'Manning', 'Marks', 'Marquez', 'Marsh', 'Marshall',
  'Martin', 'Mason', 'Massey', 'Mathews', 'Mathis', 'Matthews', 'Maxwell', 'May', 'Mayer', 'Maynard',
  'Mayo', 'Mays', 'Mcbride', 'Mccall', 'Mccarthy', 'Mccarty', 'Mcclain', 'Mcclure', 'Mcconnell',
  'Mccormick', 'Mccoy', 'Mccracken', 'Mccullough', 'Mcdaniel', 'Mcdonald', 'Mcdowell', 'Mcfadden',
  'Mcfarland', 'Mcgee', 'Mcguire', 'Mcintosh', 'Mckay', 'Mckee', 'Mckenzie', 'Mckinney', 'Mcknight',
  'Mclaughlin', 'Mclean', 'Mcleod', 'Mcmahon', 'Mcmillan', 'Mcneil', 'Mcpherson', 'Meadows', 'Medina',
  'Mejia', 'Melendez', 'Melton', 'Mendez', 'Mendoza', 'Meyer', 'Meyers', 'Michael', 'Middleton',
  'Miles', 'Miller', 'Mills', 'Miranda', 'Mitchell', 'Molina', 'Monroe', 'Montgomery', 'Montoya',
  'Moody', 'Moon', 'Mooney', 'Moore', 'Morales', 'Moran', 'Moreno', 'Morgan', 'Morris', 'Morrison',
  'Morrow', 'Morse', 'Morton', 'Moses', 'Mosley', 'Moss', 'Mueller', 'Mullen', 'Mullins', 'Munoz',
  'Murphy', 'Murray', 'Myers', 'Myrick', 'Nash', 'Navarro', 'Neal', 'Nelson', 'Newman', 'Newton',
  'Nguyen', 'Nichols', 'Nicholson', 'Nielsen', 'Nieves', 'Nixon', 'Noble', 'Nolan', 'Norman', 'Norris',
  'Norton', 'Nunez', 'Obrien', 'Ochoa', 'Oconnor', 'Odom', 'Odonnell', 'Oliver', 'Olsen', 'Olson',
  'Oneal', 'Oneill', 'Orr', 'Ortega', 'Ortiz', 'Osborn', 'Osborne', 'Owen', 'Owens', 'Pace',
  'Pacheco', 'Padilla', 'Page', 'Palmer', 'Park', 'Parker', 'Parks', 'Parrish', 'Parsons', 'Pate',
  'Patel', 'Patrick', 'Patterson', 'Patton', 'Paul', 'Payne', 'Pearson', 'Peck', 'Pena', 'Pennington',
  'Perez', 'Perkins', 'Perry', 'Peters', 'Petersen', 'Peterson', 'Petty', 'Phelps', 'Phillips',
  'Pickett', 'Pierce', 'Pittman', 'Pitts', 'Pollard', 'Poole', 'Pope', 'Porter', 'Potter', 'Potts',
  'Powell', 'Powers', 'Pratt', 'Preston', 'Price', 'Prince', 'Pruitt', 'Puckett', 'Pugh', 'Quinn',
  'Ramirez', 'Ramos', 'Ramsey', 'Randall', 'Randolph', 'Rangel', 'Rankin', 'Rasmussen', 'Ray', 'Raymond',
  'Reed', 'Reese', 'Reeves', 'Reid', 'Reilly', 'Reynolds', 'Rhodes', 'Rice', 'Rich', 'Richards',
  'Richardson', 'Richmond', 'Riddle', 'Riggs', 'Riley', 'Rios', 'Rivas', 'Rivera', 'Rivers', 'Roach',
  'Robbins', 'Roberson', 'Roberts', 'Robertson', 'Robinson', 'Robles', 'Rocha', 'Rodgers', 'Rodriguez',
  'Rogers', 'Rojas', 'Rollins', 'Roman', 'Romero', 'Rosa', 'Rosales', 'Rosario', 'Rose', 'Ross',
  'Roth', 'Rowe', 'Rowland', 'Roy', 'Ruiz', 'Rush', 'Russell', 'Russo', 'Rutledge', 'Ryan',
  'Salas', 'Salazar', 'Salinas', 'Sampson', 'Sanchez', 'Sanders', 'Sandoval', 'Sanford', 'Santana',
  'Santiago', 'Santos', 'Sargent', 'Saunders', 'Savage', 'Sawyer', 'Schmidt', 'Schneider', 'Schroeder',
  'Schultz', 'Schwartz', 'Scott', 'Sears', 'Sellers', 'Serrano', 'Sexton', 'Shaffer', 'Shannon',
  'Sharp', 'Shaw', 'Shelton', 'Shepard', 'Shepherd', 'Sheppard', 'Sherman', 'Shields', 'Short',
  'Silva', 'Simmons', 'Simon', 'Simpson', 'Sims', 'Singleton', 'Skinner', 'Slater', 'Small',
  'Smith', 'Snider', 'Snow', 'Snyder', 'Solomon', 'Sosa', 'Soto', 'Sparks', 'Spencer', 'Stafford',
  'Stanley', 'Stanton', 'Stark', 'Steele', 'Stein', 'Stephens', 'Stephenson', 'Stevens', 'Stevenson',
  'Stewart', 'Stokes', 'Stone', 'Stout', 'Strickland', 'Stringer', 'Strong', 'Stuart', 'Sullivan',
  'Summers', 'Sutton', 'Swanson', 'Sweeney', 'Sweet', 'Sykes', 'Talley', 'Tanner', 'Tate', 'Taylor',
  'Terrell', 'Terry', 'Thomas', 'Thompson', 'Thornton', 'Tillman', 'Todd', 'Torres', 'Townsend',
  'Tran', 'Travis', 'Trevino', 'Tucker', 'Turner', 'Tyler', 'Tyson', 'Underwood', 'Valdez',
  'Valencia', 'Valentine', 'Valenzuela', 'Vance', 'Vang', 'Vargas', 'Vasquez', 'Vaughan', 'Vaughn',
  'Vazquez', 'Vega', 'Velasquez', 'Velazquez', 'Velez', 'Villarreal', 'Vincent', 'Vinson', 'Wade',
  'Wagner', 'Walker', 'Wall', 'Wallace', 'Waller', 'Walls', 'Walsh', 'Walter', 'Walters', 'Walton',
  'Ward', 'Ware', 'Warner', 'Warren', 'Washington', 'Waters', 'Watkins', 'Watson', 'Watts', 'Weaver',
  'Webb', 'Weber', 'Webster', 'Weeks', 'Weiss', 'Welch', 'Wells', 'West', 'Wheeler', 'Whitaker',
  'White', 'Whitehead', 'Whitfield', 'Whitley', 'Whitney', 'Wiggins', 'Wilcox', 'Wilder', 'Wiley',
  'Wilkerson', 'Wilkins', 'Wilkinson', 'Williams', 'Williamson', 'Willis', 'Wilson', 'Winters',
  'Wise', 'Witt', 'Wolf', 'Wolfe', 'Wong', 'Wood', 'Woodard', 'Woods', 'Woodward', 'Wooten',
  'Workman', 'Wright', 'Wyatt', 'Wynn', 'Yang', 'Yates', 'York', 'Young', 'Zamora', 'Zavala',
  'Zimmerman', 'Zuniga'
];

// Export the expanded names
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { EXPANDED_FIRST_NAMES, EXPANDED_LAST_NAMES };
} else {
  // Make available globally for browser
  window.EXPANDED_FIRST_NAMES = EXPANDED_FIRST_NAMES;
  window.EXPANDED_LAST_NAMES = EXPANDED_LAST_NAMES;
  
  // Also update the existing global arrays for compatibility
  window.FIRST_NAMES = EXPANDED_FIRST_NAMES;
  window.LAST_NAMES = EXPANDED_LAST_NAMES;
}

console.log(`Loaded ${EXPANDED_FIRST_NAMES.length} first names and ${EXPANDED_LAST_NAMES.length} last names`);
console.log(`This provides ${EXPANDED_FIRST_NAMES.length * EXPANDED_LAST_NAMES.length} possible name combinations`);
